version: '3.7'

volumes:
  data:
    driver: local
services:
  auth:
    ports:
      - "3000:3000"
    restart: 'unless-stopped'
    build:     
      context: ../
      dockerfile: services/auth/Dockerfile
      target: prod-server
  postgres:
    image: postgres:9.6
    environment:
      POSTGRES_USER: apart
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: auth
    restart: 'unless-stopped'
    ports:
      - 5432:5432